Support for gpt partitions, and hybrid partitions
GenPi64/Build.Dist pull request #102
Opened 2021-04-11 19:52 UTC by jonesmz

Not fully tested, PR opened for review feedback.

2021-04-11 19:53 UTC, jonesmz commented on config/config.py
> +                'partuuid': UUID[:8]+'-01',
We can't support booting from gpt partitioned disks if we implicitly append -01 / -02 to the uuid in all of the scripts.

This config change lets us more expliclty say what the partition's uuid is.

2021-04-11 19:53 UTC, jonesmz commented on config/config.py
> +                'name': 'bootfs',
Instead of setting the name of every partition to "primary"...

2021-04-11 19:54 UTC, jonesmz commented on config/config.py
> +                'start': '1MiB',
Instead of relying on inconsistent behavior from parted / fdisk / gdisk, just require that the config say exactly what the start and end of the partitions are.

This supports partition layouts with holes in it as well, if someone ever wants to do that.

2021-04-11 19:55 UTC, jonesmz commented on parsers/buildimage/buildimage
> -#!/usr/bin/python3.9
File unused by anything. Deleting.

2021-04-11 19:55 UTC, jonesmz commented on parsers/cmdline/cmdline
> +    e = dict(PARTUUID=image['partitions'[p]['partuuid'], fstype=image['partitions'][p]['format'])
This is the implicit addition of -01 / -02 to the end of the partition uuid, which doesn't work with gpt partitioned disks.

2021-04-11 20:05 UTC, jonesmz commented on parsers/makeimage/makeimage
> +    p.stdin.write(f"a\n1\nt\nc\nw\n".encode('charmap'))
Currently hard coded, and not driven by the config.

Basically, for the rpi4, gpt by itself works just fine out of the box.

For the rpi3, the only way to boot gpt is using a hybrid mbr, and experimentation demonstrates that:

1) The hybrid MBR must have the first partition as the boot partition, not the special partition that stores the gpt partition table.
2) The first partition must have the boot flag set.
3) The first partition must have the type "W95 FAT32 (LBA)", which corresponds to "t", "1", "c" in fdisk. Apparently fdisk automatically sets the lba flag if you tell it to use "W95 FAT32 (LBA)".

Unfortunately, I cannot find any way to set the lba flag directly on a hybrid gpt/mbr partition setup. I wanted to use "sfdisk --type=mbr --part-attrs" or something like that to set the flag, but sfdisk doesn't let you tell it to ignore gpt, only fdisk does. Parted has no flag to tell it to work only on the mbr, and not the gpt.


To make this config driven, we would want to provide options for "hybridparttype" and "hybridpartuuid" that only get used if the config for that disk is set to hybrid.

2021-04-11 20:06 UTC, jonesmz commented on parsers/makeimage/makeimage
> +    os.system(f"sgdisk --hybrid=1:EE {LOOP}")
Make a hybrid mbr on the disk, with only two partitions.

1) The /boot partition
2) A special partition that stores the gpt partition table.

2021-04-11 20:07 UTC, jonesmz commented on parsers/makeimage/makeimage
> +    os.system(f"sgdisk --hybrid=1:EE {LOOP}")
Notably we don't bother adding the /root partition to the hybrid MBR. It's not necessary to get the rpi3 to boot, so why bother? Only provides more ways to get screwed up later.

2021-04-11 20:09 UTC, jonesmz commented on parsers/makeimage/makeimage
> +if image['format'] == 'hybrid':
Additional detail:

Doing dynamic partition resize on first boot with a hybrid mbr *does* require that we repeat the steps below after the partition operation finishes, or the gpt partition table will be in a "damaged" state after the resize. This is because gpt puts a partition table at the front and back of the disk, and the resize will overwrite the secondary gpt partition table, so we need to repair the gpt partition, which will then mess up the hybrid mbr. So we just run the commands to re-create the hybrid mbr after repartitioning. Easy peasy.

2021-04-11 20:09 UTC, jonesmz commented on parsers/makeimage/makeimage
> -            system(f"parted --script {image['name']} set {idx+1} {f} {v}")
We were setting the flags on the image file, and not the loop device. I bet that was what caused weird problems with the flags not showing up properly.

2021-04-11 20:10 UTC, jonesmz commented on parsers/makeimage/makeimage
> +if "msdos" == image['format']
This last block just prints out the partition information after everything's finished.

2021-04-12 14:41 UTC, samip5 commented on parsers/buildimage/buildimage
> -#!/usr/bin/python3.9
I don't know why the sudoers thing is in this script, maybe @perkinslr can shed some light on it?

2021-04-13 04:49 UTC, perkinslr commented on parsers/buildimage/buildimage
> -#!/usr/bin/python3.9
Historical reasons, it doesn't work, so may as well get rid of it.

2021-04-13 04:51 UTC, perkinslr commented on parsers/makeimage/makeimage
> +if image['format'] == 'hybrid':
This needs to get done inside the initramfs then, yes?

2021-04-13 04:52 UTC, perkinslr commented on parsers/makeimage/makeimage
> -            system(f"parted --script {image['name']} set {idx+1} {f} {v}")
I believe we settled on doing it to the file directly due to oddities trying to use the loop device.  So long as it works though, good enough.

2021-05-14 05:14 UTC, jonesmz commented on parsers/makeimage/makeimage
> +if image['format'] == 'hybrid':
Correct, the hybrid gpt+mbr would need to be resized, and then repaired, inside the initramfs on first boot.

2021-06-15 10:37 UTC, samip5 commented
Has this been tested yet at all?

2021-06-15 13:40 UTC, jonesmz commented
I've built images with it that boot, but I wouldnt say fully tested

2021-06-18 19:23 UTC, jonesmz commented
Rebased on main, since we merged alpha8.3

I'll build another round of images with this branch and report back.

2021-07-05 18:30 UTC, samip5 commented
> Rebased on main, since we merged alpha8.3
> 
> I'll build another round of images with this branch and report back.

How did that go or did you not get around to it?

2021-07-06 15:49 UTC, jonesmz commented
I ended up not having time to check it.

2021-08-30 23:04 UTC, samip5 requested changes
Some Python syntax issues. please fix them.

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +else
Syntax error, should be `else:`.

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +            else
Same syntax issues as above.

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +                else if "off" == v:
Wrong syntax, else if in Python is `elif`.

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +                else
Syntax

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +                else
Syntax

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +                if "boot" == f:
Should this be elif?

2021-08-30 23:04 UTC, samip5 commented on parsers/makeimage/makeimage
> +else
Syntax

2021-08-30 23:07 UTC, jonesmz commented
Good thing I asked for a review,since I'm not a python programmer. Thanks!

2021-08-30 23:10 UTC, samip5 requested changes

2021-08-30 23:10 UTC, samip5 commented on parsers/makeimage/makeimage
> +if "msdos" == image['format']
Syntax issue.

2021-08-30 23:10 UTC, samip5 commented on parsers/makeimage/makeimage
> +if "hybrid" == image['format']
Syntax

2021-08-30 23:11 UTC, samip5 commented on parsers/makeimage/makeimage
> +if "hybrid" == image['format']
Line 100 too.

2021-08-30 23:18 UTC, samip5 requested changes
Sorry for all the seperate "request changes" but didin't spot them all on the first pass. :)

2021-08-30 23:18 UTC, samip5 commented on parsers/makeimage/makeimage
>  LOOP = json.load(p.stdout)['loopdevices'][0]['name']
LOOP variable is being used on line 32, and yet it's defined here. This needs to be moved up, otherwise it ends up with a not defined error.

2021-09-03 01:50 UTC, samip5 commented
I think we could merge this, but any objections @perkinslr  @jonesmz?

2021-09-03 02:15 UTC, jonesmz commented on parsers/makeimage/makeimage
> +    system(f"parted --script {image['name']} mklabel {image['format']}")
I don't follow why parted is being called. Why isn't fdisk sufficent?

2021-09-03 02:20 UTC, jonesmz commented on parsers/makeimage/makeimage
>      p = subprocess.Popen([prted, image['name']], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
For the actual partitioning operations, we should either use losetup everywhere (except for the diagnostic printing at the very end), or we should instead only operate on the image file.

Currently the code in this PR does both inconsistantly

2021-09-03 02:23 UTC, jonesmz commented on parsers/makeimage/makeimage
> +system(f"losetup --detach {LOOP}")
Assuming the use of parted, in the above block for supporting hybrid partition tables, cannot work on loopback devices, then the loopback device must be detached *prior* to operating on the file that it points to.

Though I imagine you could just replace the use of image['name'] with LOOP and it would work fine.

2021-09-03 02:25 UTC, jonesmz commented
I can't approve my own pull request, but aside from some inconsistancies with how we're dealing with loopback vs file, it's fine with me if the PR is merged.

2021-09-03 02:35 UTC, samip5 commented on parsers/makeimage/makeimage
> +    system(f"parted --script {image['name']} mklabel {image['format']}")
Good question, git blame says it was you.

2021-09-03 03:16 UTC, jonesmz commented on parsers/makeimage/makeimage
> +    system(f"parted --script {image['name']} mklabel {image['format']}")
Ah, i see.

well the me of several months ago had his reasons, i suppose.

but the me of right now doesn't know what they are, and thinks this line should go.

2021-09-03 14:31 UTC, jonesmz commented on parsers/makeimage/makeimage
> +    system(f"parted --script {image['name']} mklabel {image['format']}")
Figured it out.

We totally borked the mbr partition type setup stuff.

Latest commit should be better.

Please let me know if i screwed up any python-isms.

2021-09-03 14:31 UTC, jonesmz commented
Added a commit to try to repair msdos partition creation. Some instructions got lost in translation in teh previous changes.

2021-09-15 16:52 UTC, samip5 approved these changes

2021-09-15 16:52 UTC, merged

2021-09-15 17:11 UTC, samip5 commented
Managed to force push in a way that it got reverted, but I added it back.

The git blame etc will be incorrect on that file but oh well.