Some minor improvements for the shell code
GenPi64/Build.Dist pull request #157
Opened 2022-05-25 23:43 UTC by maffblaster

Please review. This code improves the shell code by making the shell script consistent with best practices.

Also adds a Troubleshooting.md document that defines special 'custom' bash exit codes that should never need to be used, but would be helpful if they're ever needed.

2022-05-26 03:28 UTC, samip5 commented
Did you check that those shebangs work on non-Gentoo systems? Our builder is running Ubuntu and thus, those /bin/bash ones might not actually work.

2022-05-27 21:52 UTC, maffblaster commented
> Did you check that those shebangs work on non-Gentoo systems? Our builder is running Ubuntu and thus, those /bin/bash ones might not actually work.

As far as I can tell, all the scripts presume `bash` is being used as the shell, so I just made it consistent. Shouldn't affect any system that is currently running the builder, but no, I didn't test it. I use almost Gentoo exclusively.

2022-05-28 16:27 UTC, jonesmz commented on build.sh
> +#!/bin/bash
shebangs should point to /usr/bin/env, to do dispatched lookup of the correct location for the shell (bash, in this case).

If we aren't using bash features, might be wise to switch to sh instead. But that's pretty limiting, so no need to change it here.

2022-05-28 16:28 UTC, jonesmz commented on build.sh
> +cd "$(dirname "${0}")" || exit
This would be better accomplished with set -e, to terminate on any failure, not just this one specific failure.

Further, need to exit with an error code, to ensure the builder dies all the way.

2022-05-28 16:29 UTC, jonesmz commented on build.sh
> +export BASEDIR="${PWD}"
I'm not aware of it being possible for the PWD variable to not be set? that points to the current working directory?

2022-05-28 16:29 UTC, jonesmz commented on build.sh
> +    	if [ -n "${BTRFS_SNAPSHOTS}" ]; then
why switch from -z to -n?

should this have double [[?

2022-05-28 16:29 UTC, jonesmz commented on build.sh
> +if [ -n "${BTRFS_SNAPSHOTS}" ] ; then
double [[?

2022-05-28 16:30 UTC, jonesmz commented on build.sh
>  if test -f "${PROJECT}.json"; then
if this is testing for existence, probably should use the double [[ form, instead of the "test" program. Just for sake of consistency with the rest of the script.

2022-05-28 16:31 UTC, jonesmz commented on scripts/binfmt.sh
> +#!/bin/bash
#!/usr/bin/env bash

2022-05-28 16:31 UTC, jonesmz commented on scripts/functions.sh
> +  if [[ ! -e "${1}" ]]; then
combine these conditions into a single if statement?

2022-05-28 16:32 UTC, jonesmz requested changes
Please evaluate my feedback and re-work as appropriate

2022-05-31 19:31 UTC, jonesmz commented on build.sh
> +cd "$(dirname "${0}")" || exit
Any non-zero should work. 1 is fine.

But like I said. Use set -e instead.

2022-05-31 23:15 UTC, maffblaster commented on build.sh
> +export BASEDIR="${PWD}"
I can remove the comment if you think this is necessary, however the important part of this change is to quote the PWD value, since the path could contain a space or another special character...

As far as I know, as long as the shell is POSIX compliant it will set the PWD variable during a call to `cd` or upon shell startup.

2022-05-31 23:47 UTC, jonesmz commented on build.sh
> +export BASEDIR="${PWD}"
You can leave it, it doesn't hurt anything.

2023-05-12 10:50 UTC, samip5 commented
Quotes in file paths are not needed.

2024-01-21 22:49 UTC, samip5 commented
No activity in 8 months, closing.

2024-01-21 22:49 UTC, closed without merging