Merge the "jenkins-aws" branch to master
GenPi64/Build.Dist pull request #168
Opened 2022-09-05 16:29 UTC by jonesmz

Automated builds work now

2022-09-06 06:38 UTC, samip5 requested changes
I have reviewed what I think of it's state. I also think that the genpi-releaser thing is not ready to be merged nor the fact that builds get null prefix.

2022-09-06 06:38 UTC, samip5 commented on parsers/addsets/addsets
> +#!/bin/bash -evx
I'm not a fan of keeping the `-enx` for bash.

2022-09-06 06:38 UTC, samip5 commented on parsers/binaryWorkarounds/binaryWorkarounds
> +#!/bin/bash -evx
I'm not a fan of keeping the `-enx` for bash.

2022-09-06 06:38 UTC, samip5 commented on parsers/compress-image/compress-image
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/convertimg/convertimg
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/distcc/distcc
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/downloadstage3/downloadstage3
> +#!/bin/bash -evx
Not a fan, but probably worth keeping.

2022-09-06 06:38 UTC, samip5 commented on parsers/echo/echo
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/git/git
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/mdadm-shutdown/mdadm-shutdown
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/packstage4/packstage4
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/password/password
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/printf/printf
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/qemu/qemu
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/rawcommand/rawcommand
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/setprofile/setprofile
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/setupservices/setupservices
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/stage3/stage3
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/strip/strip
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/unmount/unmount
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/unpackstage4/unpackstage4
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/users/setupusers
> +set -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/users/users
> +#!/bin/bash -evx
Not a fan

2022-09-06 06:38 UTC, samip5 commented on parsers/utils/utils
> +#!/bin/bash -evx
Not a fan

2022-09-06 14:05 UTC, jonesmz commented on parsers/addsets/addsets
> +#!/bin/bash -evx
What's the problem with it?

2022-09-06 18:18 UTC, samip5 commented on parsers/addsets/addsets
> +#!/bin/bash -evx
> What's the problem with it?

I dislike the whole lot of things it outputs, specially if ran manually.

2022-09-07 10:16 UTC, samip5 commented
Also, they may work but some stages are still failing but are not outputting why.

2022-09-07 21:51 UTC, jonesmz commented
So you just want the -vx removed?

2022-09-08 05:53 UTC, samip5 commented
> So you just want the -vx removed?

Yes.

2022-10-13 08:06 UTC, samip5 approved these changes
LGTM now.

2022-10-13 08:07 UTC, merged