Fixup the config.txt file in /boot to add the kernel
GenPi64/Build.Dist pull request #32
Opened 2021-01-30 04:00 UTC by jonesmz

It's possible that a similar line is necessary for rpi3 as well.

Note: I did a very basic search for a dedicated ini file CLI, and couldn't find anything, so sed might not be the optimal tool for this. But it should work well enough given the grep check before running.

2021-01-30 04:05 UTC, perkinslr commented
There is an ini-file editor in the repo already: `scripts/crudini`
Not sure its API, and it depends on `dev-python/iniparse`

2021-01-30 04:23 UTC, perkinslr requested changes
{"name": "fixboot3", "deps": ["kernel"], "parser": "crudini", "args": ["--set $CHROOT_DIR/boot/config.txt '' kernel kernel8.img"]},
    {"name": "fixboot4", "deps": ["fixboot3"], "parser": "crudini", "args": ["--set $CHROOT_DIR/boot/config.txt 'pi4' kernel kernel8-pi4.img"]},

2021-01-30 04:29 UTC, jonesmz commented
crudini is it's own parser?

I don't have this on my end.

Did you submit it to alpha6?

checking  fixboot3 deps []
all deps satisfied for fixboot3
executing  fixboot3 deps []
Traceback (most recent call last):
  File "/root/Build.Dist/parsers/includejson/includejson", line 146, in <module>
    jobs1=jobs+execute(manifest)
  File "/root/Build.Dist/parsers/includejson/includejson", line 102, in execute
    jobs.append( (subprocess.Popen([os.path.join(os.environ['PARSERS'],item['parser'],item['parser'])]+item['args'],env=env),item['name']) )
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/Build.Dist/parsers/crudini/crudini'
run complete.

2021-01-30 04:30 UTC, jonesmz commented
Ah. You added it 12 minutes ago. "already" eh? :-P

2021-01-30 04:30 UTC, perkinslr commented
> crudini is it's own parser?
> 
> I don't have this on my end.
> 
> Did you submit it to alpha6?
> 
> checking fixboot3 deps []
> all deps satisfied for fixboot3
> executing fixboot3 deps []
> Traceback (most recent call last):
> File "/root/Build.Dist/parsers/includejson/includejson", line 146, in
> jobs1=jobs+execute(manifest)
> File "/root/Build.Dist/parsers/includejson/includejson", line 102, in execute
> jobs.append( (subprocess.Popen([os.path.join(os.environ['PARSERS'],item['parser'],item['parser'])]+item['args'],env=env),item['name']) )
> File "/usr/lib/python3.9/subprocess.py", line 947, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/root/Build.Dist/parsers/crudini/crudini'
> run complete.

Already did, you'll need to pull to catch it.  There's been a copy hanging under `scripts`, but I copied it into `parsers` so it can get used like this.

2021-01-30 04:32 UTC, jonesmz commented
all deps satisfied for fixboot3
executing  fixboot3 deps []
running jobs [(<Popen: returncode: None args: ['/root/Build.Dist/parsers/crudini/crudini', ...>, 'fixboot3')]
Traceback (most recent call last):
  File "/root/Build.Dist/parsers/crudini/crudini", line 18, in <module>
    import iniparse
ModuleNotFoundError: No module named 'iniparse'
FATAL: JOBFAILED  fixboot3
run complete.


Looks like we have a new dependency with this.

2021-01-30 04:32 UTC, jonesmz commented
dev-python/iniparse

2021-01-30 04:43 UTC, jonesmz commented
Are we lumping the arguments into a single "string", instead of splitting basted on spaces?


```
running jobs [(<Popen: returncode: None args: ['/root/Build.Dist/parsers/crudini/crudini', ...>, 'fixboot4')]
option --set --inplace --existing-file $CHROOT_DIR/boot/config.txt pi4 kernel kernel8-pi4.img not recognized
A utility for manipulating ini files

Usage: crudini --set [OPTION]...   config_file section   [param] [value]
  or:  crudini --get [OPTION]...   config_file [section] [param]
  or:  crudini --del [OPTION]...   config_file section   [param] [list value]
  or:  crudini --merge [OPTION]... config_file [section]
```

2021-01-30 04:50 UTC, jonesmz commented
Yep, we are.

So we need

```
    {"name": "fixboot3", "deps": ["kernel"], "parser": "crudini", "args": ["--set", "--inplace", "--existing=file", "$CHROOT_DIR/boot/config.txt", "''", "kernel", "kernel8.img"]},
    {"name": "fixboot4", "deps": ["fixboot3"], "parser": "crudini", "args": ["--set", "--inplace", "--existing=file", "$CHROOT_DIR/boot/config.txt", "'pi4'", "kernel", "kernel8-pi4.img"]},
```

But now we need to force python to replace $CHROOT_DIR with the appropriate environment variable.

2021-01-30 05:00 UTC, jonesmz commented
I think we would need to do the substitution of environment variables here:
```
jobs.append(subprocess.Popen([os.path.join(os.environ['PARSERS'],item['parser'],item['parser'])]+item['args'],env=env),item['name']) )
```

in the execute function.

But it's not clear to me that this is the right way to handle it at all.

2021-01-30 05:17 UTC, jonesmz commented
I think that we need a more generalized approach

Some commands from the included json file need to be run inside the chroot, and other commands need to be run outside the chroot. But all of them need to run relative to the workspace.

So I think we need the following:

1. A new key for each json line that says what the execution environment is. Starting values should be "host" or "chroot"
2. chroot mode parsers need to be able to access the code from the Build.Dist codebase, so we should always bind-mount the Build.Dist code to some directory inside the chroot when running in chroot mode. Something-something mktmp, or a directory with a UUID in it or something, to avoid collisions. 
3. A new key for specifying the directory to execute a command in. Absolute paths are evaluated as absolute paths, and relative are evaluated relative to: Hostmode: workspace directory, chroot mode: bindmount of Build.Dist directory inside the chroot.
4. A new key that only works in chroot mode that takes an array of directories / files to bind mount with the chroot. (or an array of 2 item arrays??), with relative paths being evaluated as if the CWD is the workspace directory.

An alternative to having the same key for the CWD for both host and chroot modes, we could have different keys for hostcwd and chrootcwd, though I don't know that that buys us much.

2021-01-30 05:33 UTC, jonesmz commented
We might also want to bind-mount the entire workspace directory inside the chroot as well.

something like both of these:
/tmp/$(uuidgen)-build.dist/
/tmp/$(uuidgen)-workspace/

It would be pretty stupid for someone to access 

/tmp/$(uuidgen)-workspace/chroot

but i guess it wouldn't actually *hurt* anything, so it's not a problem if they do, even if it's no more useful than accessing / inside the chroot directly.

2021-02-01 19:49 UTC, perkinslr commented
I resolved this locally and pushed the changes, so I'm closing this copy.

2021-02-01 19:49 UTC, closed without merging